language: node_js
node_js:
  - 8

cache:
  directories:
    - "node_modules"

before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
  - npm i -g greenkeeper-lockfile

before_script:
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - npx semantic-release

branches:
  only:
    - master
    - /^greenkeeper/.*$/
